version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_DB

  mongodb:
    image: mongo:latest
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./docker/app
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - "postgres:postgreshost"
      - "mongodb:mongohost"
      - "redis-queue:redishost"
    depends_on:
      postgres:
        condition: service_started
      mongodb:
        condition: service_healthy
      redis-queue:
        condition: service_started

  queue:
    build: ./docker/queue
    restart: always
    volumes:
      - .:/usr/app
    links:
      - "postgres:postgreshost"
      - "redis-queue:redishost"
    depends_on:
      - postgres
      - redis-queue

  redis-queue:
    image: "redis:alpine"
    ports:
      - "6379:6379"
