version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_DB

  app:
    build: ./docker/app
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - "postgres:postgreshost"
      - "redis-queue:redishost"
    depends_on: 
      - postgres
      - redis-queue

  queue:
    build: ./docker/queue
    restart: always
    volumes:
      - .:/usr/app
    links:
      - "postgres:postgreshost"
      - "redis-queue:redishost"
    depends_on: 
      - postgres
      - redis-queue


  redis-queue:
    image: "redis:alpine"

    ports:
      - "6379:6379"
