version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_DB

  app:
    build: .
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - "postgres:postgreshost"
    depends_on: 
      - postgres
