export type Operation =
  | "DELETE_PROJECT"
  | "UPDATE_PROJECT"
  | "CREATE_ISSUE_GROUP"
  | "CREATE_ISSUE"
  | "DELETE_ISSUE"
  | "UPDATE_ISSUE"
  | "INVITE_ACCOUNT_TO_PROJECT"
  | "KICK_ACCOUNT_FROM_PROJECT"
  | "REVOKE_INVITATION"
  | "UPDATE_PARTICIPANT_ROLE"
  | "MOVE_ISSUE"
  | "ASSIGN_ISSUE_TO_ACCOUNT";
